name: Semantic Release

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Show current branch (debug)
        run: git branch --show-current
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
            
      - name: Run semantic-release version only (no push)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sr() {
            uvx --from="python-semantic-release@9.21.1" semantic-release "$@"
          }
          sr version --no-push
      
      - name: Create Pull Request for Release
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): bump version"
          branch: release/automated
          delete-branch: true
          title: "chore(release): new version"
          body: |
            Automated release PR created by semantic-release
