name: Publish Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python: "3.13"

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          uvx --from="python-semantic-release@9.21.1" semantic-release publish \
            --tag \
            --changelog \
            --vcs-release