name: Semantic Release

on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
            
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: | #shell
          sr() {
              uvx --from="python-semantic-release@9.21.1" semantic-release "$@"
            }
          sr version
          sr publish
    
